"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

interface RepeatedWord { word: string; count: number; frequencyPerThousand: number; scenes: string[]; suggestions: string[] }
interface EpisodeAnalysis { episodeId: string | null; episodeTitle: string; sceneCount: number; wordCount: number; repeatedWords: RepeatedWord[] }

export default function RepetitionAnalysisPage() {
  const { projectId } = useParams() as { projectId: string }; const [minimum, setMinimum] = useState(3); const [episodes, setEpisodes] = useState<EpisodeAnalysis[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { setLoading(true); setError(null); fetch(`/api/projects/${projectId}/analysis/repetitions?minimum=${minimum}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setEpisodes(data.episodes); }).catch((reason) => setError(reason.message || "Analyse impossible")).finally(() => setLoading(false)); }, [projectId, minimum]);
  return <div className="min-h-screen"><header className="border-b border-narra-border"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-4 sm:flex-row sm:items-end sm:justify-between sm:px-6"><div><Link href={`/project/${projectId}`} className="text-sm text-narra-muted hover:text-narra-text">← Retour</Link><h1 className="mt-2 text-xl font-bold">Répétitions par épisode</h1><p className="mt-1 text-sm text-narra-muted">Repérez les mots dominants et explorez des remplacements possibles.</p></div><label className="text-sm"><span className="mr-2 text-narra-muted">Seuil</span><select className="select inline-block w-auto" value={minimum} onChange={(e) => setMinimum(Number(e.target.value))}>{[2,3,4,5,8,10].map((value) => <option key={value} value={value}>{value} occurrences</option>)}</select></label></div></header><main className="mx-auto max-w-6xl space-y-8 px-4 py-6 sm:px-6">{loading ? <p className="text-narra-muted">Analyse des scènes…</p> : error ? <p role="alert" className="text-narra-danger">{error}</p> : episodes.length === 0 ? <div className="card p-10 text-center text-narra-muted">Ajoutez des scènes et du texte pour lancer l’analyse.</div> : episodes.map((episode) => <section key={episode.episodeId || "none"}><div className="mb-3 flex flex-wrap items-baseline justify-between gap-2 border-b border-narra-border pb-3"><h2 className="text-lg font-semibold">{episode.episodeTitle}</h2><p className="text-xs tabular-nums text-narra-muted">{episode.wordCount} mots · {episode.sceneCount} scène{episode.sceneCount === 1 ? "" : "s"}</p></div>{episode.repeatedWords.length === 0 ? <p className="text-sm text-narra-muted">Aucune répétition au-dessus du seuil.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-narra-muted"><tr><th className="py-2 pr-4">Mot</th><th className="py-2 pr-4">Occurrences</th><th className="py-2 pr-4">Fréquence</th><th className="py-2 pr-4">Scènes</th><th className="py-2">Suggestions</th></tr></thead><tbody className="divide-y divide-narra-border">{episode.repeatedWords.map((item) => <tr key={item.word}><td className="py-3 pr-4 font-semibold text-narra-accent">{item.word}</td><td className="py-3 pr-4 tabular-nums">{item.count}</td><td className="py-3 pr-4 tabular-nums text-narra-muted">{item.frequencyPerThousand} ‰</td><td className="max-w-xs py-3 pr-4 text-narra-muted">{item.scenes.join(", ")}</td><td className="py-3">{item.suggestions.length ? item.suggestions.join(" · ") : <span className="text-narra-muted">Contexte à vérifier</span>}</td></tr>)}</tbody></table></div>}</section>)}</main></div>;
}
