"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";

interface Option { id: string; name?: string; title?: string; alias?: string; firstName?: string | null; lastName?: string | null }

export default function NewTimelineEventPage() {
  const { projectId } = useParams() as { projectId: string }; const router = useRouter();
  const [locations, setLocations] = useState<Option[]>([]); const [characters, setCharacters] = useState<Option[]>([]); const [organizations, setOrganizations] = useState<Option[]>([]); const [scenes, setScenes] = useState<Option[]>([]);
  const [form, setForm] = useState({ title: "", narrativeDate: "", sortKey: "", description: "", locationId: "", characterIds: [] as string[], organizationIds: [] as string[], sceneIds: [] as string[] });
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all(["locations", "characters", "organizations", "scenes"].map((name) => fetch(`/api/projects/${projectId}/${name}`).then((response) => response.ok ? response.json() : []))).then(([l, c, o, s]) => { setLocations(l); setCharacters(c); setOrganizations(o); setScenes(s); }); }, [projectId]);
  function update(field: string, value: string | string[]) { setForm((current) => ({ ...current, [field]: value })); }
  function toggle(field: "characterIds" | "organizationIds" | "sceneIds", id: string) { const values = form[field]; update(field, values.includes(id) ? values.filter((value) => value !== id) : [...values, id]); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const payload = { ...form, locationId: form.locationId || undefined, narrativeDate: form.narrativeDate || undefined, sortKey: form.sortKey || form.narrativeDate || undefined, description: form.description || undefined }; const response = await fetch(`/api/projects/${projectId}/timeline`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Impossible de créer l’événement"); router.push(`/project/${projectId}/timeline`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Impossible de créer l’événement"); } finally { setSaving(false); } }
  return <div className="min-h-screen"><header className="border-b border-narra-border"><div className="mx-auto max-w-5xl px-4 py-4 sm:px-6"><Link href={`/project/${projectId}/timeline`} className="text-sm text-narra-muted hover:text-narra-text">← Timeline</Link><h1 className="mt-2 text-xl font-bold">Nouvel événement</h1></div></header><main className="mx-auto max-w-5xl px-4 py-6 sm:px-6"><form onSubmit={submit} className="space-y-6">{error && <p role="alert" className="border border-narra-danger p-3 text-sm text-narra-danger">{error}</p>}<div className="grid gap-4 sm:grid-cols-2"><Field id="event-title" label="Titre"><input id="event-title" className="input" required maxLength={200} value={form.title} onChange={(e) => update("title", e.target.value)} autoFocus /></Field><Field id="event-date" label="Date narrative"><input id="event-date" className="input" maxLength={200} value={form.narrativeDate} onChange={(e) => update("narrativeDate", e.target.value)} placeholder="Ex. An 2087, Jour 14" /></Field><Field id="event-sort" label="Clé de tri"><input id="event-sort" className="input" maxLength={100} value={form.sortKey} onChange={(e) => update("sortKey", e.target.value)} placeholder="Ex. 2087-014" /></Field><Field id="event-location" label="Lieu"><select id="event-location" className="select" value={form.locationId} onChange={(e) => update("locationId", e.target.value)}><option value="">Aucun</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><Field id="event-description" label="Description"><textarea id="event-description" className="textarea" rows={5} maxLength={10000} value={form.description} onChange={(e) => update("description", e.target.value)} /></Field><div className="grid gap-5 lg:grid-cols-3"><Checklist title="Personnages" options={characters} selected={form.characterIds} onToggle={(id) => toggle("characterIds", id)} label={(item) => item.alias || `${item.firstName || ""} ${item.lastName || ""}`.trim()} /><Checklist title="Organisations" options={organizations} selected={form.organizationIds} onToggle={(id) => toggle("organizationIds", id)} label={(item) => item.name || ""} /><Checklist title="Scènes" options={scenes} selected={form.sceneIds} onToggle={(id) => toggle("sceneIds", id)} label={(item) => item.title || ""} /></div><div className="flex gap-3 border-t border-narra-border pt-5"><button className="btn-primary" disabled={saving}>{saving ? "Création…" : "Ajouter à la frise"}</button><Link href={`/project/${projectId}/timeline`} className="btn">Annuler</Link></div></form></main></div>;
}
function Field({ id, label, children }: { id: string; label: string; children: React.ReactNode }) { return <div><label htmlFor={id} className="label">{label}</label>{children}</div>; }
function Checklist({ title, options, selected, onToggle, label }: { title: string; options: Option[]; selected: string[]; onToggle: (id: string) => void; label: (item: Option) => string }) { return <fieldset className="border border-narra-border p-3"><legend className="px-1 text-xs font-medium uppercase tracking-wider text-narra-muted">{title}</legend><div className="max-h-40 space-y-2 overflow-y-auto scrollbar-thin">{options.length ? options.map((item) => <label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} className="accent-amber-500" /><span className="truncate">{label(item)}</span></label>) : <p className="text-xs text-narra-muted">Aucun élément disponible.</p>}</div></fieldset>; }
